#featurebook-api
sudo: false

language: node_js

node_js:
  - "12"
  - "10"
  - "8"

after_script:
  - npm run coverage
  - npm run coveragetocodeclimate
---
#featurebook-gherkin
sudo: false

language: node_js

node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

after_script:
  - npm run coverage
  - npm run coveragetocodeclimate
---
#featurebook-serve
sudo: false

language: node_js

node_js:
  - "12"
  - "10"
  - "8"

after_script:
  - npm run coverage
  - npm run coveragetocodeclimate
---
#featurebook-pdf
sudo: false

language: node_js

node_js:
  - "12"
  - "10"
  - "8"

after_script:
  - npm run coverage
  - npm run coveragetocodeclimate

