name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 1 * * *'

jobs:
  featurebook:
    strategy:
      matrix:
        node: [ '8', '10', '12' ]
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: cd packages/featurebook
      - run: npm ci
      - run: npm run lint
      - run: npm run test

  featurebook-api:
    strategy:
      matrix:
        node: [ '8', '10', '12' ]
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: cd packages/featurebook-api
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: npm run coverage
      - run: npm run coveragetocodeclimate
  featurebook-html:
    strategy:
      matrix:
        node: [ '8', '10', '12' ]
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: cd packages/featurebook-html
      - run: npm ci
      - run: npm run lint
      - run: npm run test
  featurebook-markdown:
    strategy:
      matrix:
        node: [ '8', '10', '12' ]
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: cd packages/featurebook-markdown
      - run: npm ci
      - run: npm run lint
      - run: npm run test
  featurebook-pdf:
    strategy:
      matrix:
        node: [ '8', '10', '12' ]
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: cd packages/featurebook-pdf
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: npm run coverage
      - run: npm run coveragetocodeclimate
  featurebook-serve:
    strategy:
      matrix:
        node: [ '8', '10', '12' ]
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: cd packages/featurebook-serve
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: npm run coverage
      - run: npm run coveragetocodeclimate
