name: CI featurebook-js (code climate)

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm bootstrap
      - run: npx lerna run coverage
      - run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          for f in packages/*; do
            if [ -d $f ]; then
              echo $f;
              ./cc-test-reporter format-coverage -t lcov -o coverage/coverage.${f//\//-}.json $f/coverage/lcov.info;
            fi
          done;
          ./cc-test-reporter sum-coverage -o coverage/coverage.total.json coverage/coverage.*.json;
          ./cc-test-reporter upload-coverage -i coverage/coverage.total.json;
        env:
          CC_TEST_REPORTER_ID: 18908f02e2f04c41f84ac447800fdca9a1fae3a15ba319228a4484408d827111
