name: CI featurebook

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  node:
    strategy:
      matrix:
        node: [ '8', '10', '12' ]
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npx lerna bootstrap
      - name: code climate
        working-directory: packages/featurebook-api
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: 18908f02e2f04c41f84ac447800fdca9a1fae3a15ba319228a4484408d827111
        with:
          coverageCommand: npx lerna run coverage
          debug: true
